import type { Metadata } from "next";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";
import { ClerkProvider } from "@clerk/nextjs";

// import Head from "../Head";
import Header from "../../components/Header";
import { SanityLive } from "@/sanity/lib/live";
// import Mouse from "@/components/sectionalComponents/Mouse";
import { DisableDraftMode } from "../../components/DisableDraftMode";

import "../../styles/globals.css";
import MyApp from "@/pages/_app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        {/* <Head /> */}
        {/* <Mouse /> */}
        <body>
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}

            <Header />
            {children}

          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
};

// import type { Metadata } from "next";
// import { draftMode } from "next/headers";
// import { VisualEditing } from "next-sanity";
// import { ClerkProvider } from "@clerk/nextjs";

// import Header from "@/components/Header";
// import { SanityLive } from "@/sanity/lib/live";
// import { DisableDraftMode } from "@/components/DisableDraftMode";

// import "../globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider dynamic>
//       <html lang="en">
//         <body>
//           {(await draftMode()).isEnabled && (
//             <>
//             <DisableDraftMode/>
//             <VisualEditing/>
//             </>
//           )}
//           <main>
//             <Header/>  
//             {children}
//           </main>
//           <SanityLive />
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// };